services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: --replSet="rs0"
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.Bot
    links:
      - mongodb
    stdin_open: true
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
